name: Pre-build checks

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  lint_check:
    name: Lint the code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build and run Dev Container task
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          poetry run ruff -v ./langchain_weaviate/ ./tests/
  
  format_check:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build and run Dev Container task
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          poetry run ruff format -v --diff ./langchain_weaviate/ ./tests/